<a href="https://colab.research.google.com/github/SaipoojithaNamani/python8/blob/main/python8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:
k=[4,6,2.5,56789,9,87.9999,40,]
k

[4, 6, 2.5, 56789, 9, 87.9999, 40]

In [ ]:
pd.Series(k)

0        4.0000
1        6.0000
2        2.5000
3    56789.0000
4        9.0000
5       87.9999
6       40.0000
dtype: float64

In [ ]:
a=np.random.randint(20,50,(5,4))
a

array([[26, 43, 21, 27],
       [31, 34, 29, 49],
       [38, 23, 27, 22],
       [35, 23, 23, 27],
       [44, 44, 41, 36]])

In [ ]:
a.ndim

2

In [ ]:
s=pd.series(a)

AttributeError: module 'pandas' has no attribute 'series'

In [ ]:
s=a=np.random.randint(30,50,(5,4))
a

array([[44, 34, 44, 35],
       [38, 39, 30, 42],
       [40, 32, 48, 41],
       [36, 34, 49, 38],
       [35, 48, 46, 42]])

In [ ]:
s

array([[44, 34, 44, 35],
       [38, 39, 30, 42],
       [40, 32, 48, 41],
       [36, 34, 49, 38],
       [35, 48, 46, 42]])

In [ ]:
np.random.seed(34)
b=np.random.randint(100,200,(6,5))
b

array([[133, 185, 168, 135, 169],
       [111, 178, 129, 118, 129],
       [189, 129, 120, 196, 162],
       [105, 120, 151, 119, 185],
       [121, 163, 172, 142, 184],
       [172, 177, 136, 102, 137]])

In [ ]:
b.ndim

2

In [ ]:
b

array([[133, 185, 168, 135, 169],
       [111, 178, 129, 118, 129],
       [189, 129, 120, 196, 162],
       [105, 120, 151, 119, 185],
       [121, 163, 172, 142, 184],
       [172, 177, 136, 102, 137]])

In [ ]:
df=pd.DataFrame(b)
df

0    1    2    3    4
0  133  185  168  135  169
1  111  178  129  118  129
2  189  129  120  196  162
3  105  120  151  119  185
4  121  163  172  142  184
5  172  177  136  102  137

In [ ]:
df.iloc[0,0]

133

In [ ]:
df.iloc[4,3]

142

In [ ]:
df.iloc[0,0:3]

0    133
1    185
2    168
Name: 0, dtype: int64

In [ ]:
df.iloc[[0,5]]

0    1    2    3    4
0  133  185  168  135  169
5  172  177  136  102  137

In [ ]:
df.iloc[[1,3,4]]

0    1    2    3    4
1  111  178  129  118  129
3  105  120  151  119  185
4  121  163  172  142  184

In [ ]:
df

0    1    2    3    4
0  133  185  168  135  169
1  111  178  129  118  129
2  189  129  120  196  162
3  105  120  151  119  185
4  121  163  172  142  184
5  172  177  136  102  137

In [ ]:
df[[3]]

3
0  135
1  118
2  196
3  119
4  142
5  102

In [ ]:
df[[0]]

0
0  133
1  111
2  189
3  105
4  121
5  172

In [ ]:
df[[4]]

4
0  169
1  129
2  162
3  185
4  184
5  137

In [ ]:
df[[0,1,4]]

0    1    4
0  133  185  169
1  111  178  129
2  189  129  162
3  105  120  185
4  121  163  184
5  172  177  137

In [ ]:
df.loc[[0,1,4]],[2,4,3]

(     0    1    2    3    4
 0  133  185  168  135  169
 1  111  178  129  118  129
 4  121  163  172  142  184,
 [2, 4, 3])

In [ ]:
sns.get_dataset_names

<function seaborn.utils.get_dataset_names()>

In [ ]:
df=sns.load_dataset('diamonds')

In [ ]:
df.shape

(6, 5)

In [ ]:
df.columns

RangeIndex(start=0, stop=5, step=1)

In [ ]:
type(df)

pandas.core.frame.DataFrame